name: Sync fork with upstream

on:
  schedule:
    - cron: '0 */8 * * *'
      timezone: "Asia/Shanghai"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Divinci-AI/sync-fork-action@v1
        with:
          upstream_repository: cmliu/edgetunnel
          upstream_branch: main
          target_branch: main
